export const vocabDict = {
    "jetpacks": "A device worn on the back that uses gas or water to push someone into the air.",
    "cuisine": "A style or method of cooking, typical of a specific region.",
    "siblings": "Brothers or sisters.",
    "hometown": "The town or city where you grew up.",
    "taboo": "A topic or word that is avoided or forbidden.",
    "bilingual": "Able to speak two languages fluently.",
    "therapy": "Treatment intended to relieve or heal a problem.",
    "rapid-fire": "A series of questions asked very quickly.",
    "admire": "To look at with respect or warm approval.",
    "routines": "A sequence of actions regularly followed.",
    "instruments": "A tool or device used for playing music."
};

export type QuestionType = "question" | "challenge";

export interface DeckItem {
    id: number;
    text_en: string;
    text_tr: string;
    type: QuestionType;
}

export const DECK: DeckItem[] = [
    { id: 1, text_en: "What is the meaning of your name?", text_tr: "Adının anlamı nedir?", type: "question" },
    { id: 2, text_en: "Money no object! Everybody gets jetpacks! Tell me what are you going to do with your life!", text_tr: "Para sorun değil! Herkese jetpack! Hayatınla ne yapacaksın anlat!", type: "challenge" },
    { id: 3, text_en: "What's your favorite food?", text_tr: "En sevdiğin yemek nedir?", type: "question" },
    { id: 4, text_en: "Do you play any video games?", text_tr: "Hiç video oyunu oynar mısın?", type: "challenge" },
    { id: 5, text_en: "Which app do you open first in the morning?", text_tr: "Sabah ilk olarak hangi uygulamayı açarsın?", type: "question" },
    { id: 6, text_en: "What's something you always carry with you?", text_tr: "Yanında her zaman taşıdığın bir şey nedir?", type: "question" },
    { id: 7, text_en: "What do you do when you're bored?", text_tr: "Sıkıldığında ne yaparsın?", type: "challenge" },
    { id: 8, text_en: "What was the last gift you gave someone?", text_tr: "Birine verdiğin en son hediye neydi?", type: "question" },
    { id: 9, text_en: "ACT OUT the last movie you watched", text_tr: "CANLANDIR: İzlediğin son filmi canlandır.", type: "challenge" },
    { id: 10, text_en: "What's your favorite cuisine?", text_tr: "En sevdiğin mutfak hangisi?", type: "question" },
    { id: 11, text_en: "Do you have any siblings?", text_tr: "Kardeşin var mı?", type: "question" },
    { id: 12, text_en: "Tell me about your hometown", text_tr: "Bana memleketinden bahset.", type: "question" },
    { id: 13, text_en: "What's your favorite fruit?", text_tr: "En sevdiğin meyve nedir?", type: "question" },
    { id: 14, text_en: "Are you interested in any sports?", text_tr: "Herhangi bir sporla ilgileniyor musun?", type: "question" },
    { id: 15, text_en: "What is your favorite drink?", text_tr: "En sevdiğin içecek nedir?", type: "question" },
    { id: 16, text_en: "What's your favorite snack?", text_tr: "En sevdiğin atıştırmalık nedir?", type: "question" },
    { id: 17, text_en: "ASK THE TEACHER", text_tr: "ÖĞRETMENE SOR", type: "question" },
    { id: 18, text_en: "What do you do to stay healthy?", text_tr: "Sağlıklı kalmak için ne yaparsın?", type: "question" },
    { id: 19, text_en: "What fruit grows in your hometown?", text_tr: "Memleketinde hangi meyve yetişir?", type: "question" },
    { id: 20, text_en: "What vegetable grows in your hometown?", text_tr: "Memleketinde hangi sebze yetişir?", type: "question" },
    { id: 21, text_en: "TRUE or FALSE (give two different answers, player guess which is true/false)", text_tr: "DOĞRU ya da YANLIŞ (iki farklı cevap ver, oyuncular tahmin etsin)", type: "question" },
    { id: 22, text_en: "Do you have any pets?", text_tr: "Hiç evcil hayvanın var mı?", type: "question" },
    { id: 23, text_en: "Who do you live with?", text_tr: "Kiminle yaşıyorsun?", type: "question" },
    { id: 24, text_en: "What's your favorite season?", text_tr: "En sevdiğin mevsim hangisi?", type: "question" },
    { id: 25, text_en: "What's your favorite cake flavor?", text_tr: "En sevdiğin pasta aroması nedir?", type: "question" },
    { id: 26, text_en: "TABOO (describe, players guess)", text_tr: "TABU (kelimeyi anlat, diğerleri tahmin etsin)", type: "challenge" },
    { id: 27, text_en: "What's your favorite animal?", text_tr: "En sevdiğin hayvan nedir?", type: "question" },
    { id: 28, text_en: "What's your favorite vegetable?", text_tr: "En sevdiğin sebze nedir?", type: "question" },
    { id: 29, text_en: "What gift would you like to receive?", text_tr: "Ne tür bir hediye almak istersin?", type: "question" },
    { id: 30, text_en: "Do you exercise?", text_tr: "Egzersiz yapar mısın?", type: "question" },
    { id: 31, text_en: "Are you reading any books right now?", text_tr: "Şu sıralar herhangi bir kitap okuyor musun?", type: "question" },
    { id: 32, text_en: "How many languages do you speak?", text_tr: "Kaç dil biliyorsun?", type: "question" },
    { id: 33, text_en: "LIAR LIAR PANTS ON FIRE", text_tr: "YALANCININ MUMU (Yalan söyleme oyunu)", type: "challenge" },
    { id: 34, text_en: "What do you do?", text_tr: "Ne iş yapıyorsun?", type: "question" },
    { id: 35, text_en: "Is there a country you want to visit?", text_tr: "Ziyaret etmek istediğin bir ülke var mı?", type: "question" },
    { id: 36, text_en: "What is your favorite TV show?", text_tr: "En sevdiğin TV şovu nedir?", type: "challenge" },
    { id: 37, text_en: "Do you usually walk, speed-walk, or run?", text_tr: "Genelde yürür müsün, tempolu mu yürürsün, yoksa koşar mısın?", type: "question" },
    { id: 38, text_en: "ANSWER AS... (someone or another player, role play)", text_tr: "GİBİ CEVAP VER... (başka biri gibi rol yap)", type: "challenge" },
    { id: 39, text_en: "What's your favorite number?", text_tr: "En sevdiğin sayı kaçtır?", type: "question" },
    { id: 40, text_en: "What memory makes you smile?", text_tr: "Seni gülümseten bir anın nedir?", type: "question" },
    { id: 41, text_en: "What are your hobbies?", text_tr: "Hobilerin nelerdir?", type: "question" },
    { id: 42, text_en: "What are your favorite colors?", text_tr: "En sevdiğin renkler nelerdir?", type: "question" },
    { id: 43, text_en: "What kind of music do you like?", text_tr: "Ne tür müziklerden hoşlanırsın?", type: "question" },
    { id: 44, text_en: "Do you cook? / Can you cook?", text_tr: "Yemek yapar mısın? / Yapabilir misin?", type: "question" },
    { id: 45, text_en: "SING IT What is your favorite song at the moment?", text_tr: "ŞARKI SÖYLE: Şu anki en sevdiğin şarkı nedir?", type: "challenge" },
    { id: 46, text_en: "Do you play any instruments?", text_tr: "Herhangi bir enstrüman çalıyor musun?", type: "challenge" },
    { id: 47, text_en: "How do you feel when it rains?", text_tr: "Yağmur yağdığında nasıl hissedersin?", type: "question" },
    { id: 48, text_en: "Do you collect anything?", text_tr: "Bir şeylerin koleksiyonunu yapar mısın?", type: "question" },
    { id: 49, text_en: "What's your favorite smell?", text_tr: "En sevdiğin koku nedir?", type: "question" },
    { id: 50, text_en: "RANDOM FACT", text_tr: "RASTGELE BİLGİ", type: "question" },
    { id: 51, text_en: "What's something you do to organize your life?", text_tr: "Hayatını düzenlemek için yaptığın bir şey nedir?", type: "question" },
    { id: 52, text_en: "GUESS MY ANSWER", text_tr: "CEVABIMI TAHMİN ET", type: "challenge" },
    { id: 53, text_en: "What's something you want to improve about yourself?", text_tr: "Kendinle ilgili geliştirmek istediğin bir şey nedir?", type: "question" },
    { id: 54, text_en: "What's a skill you'd like to learn?", text_tr: "Öğrenmek istediğin bir beceri nedir?", type: "challenge" },
    { id: 55, text_en: "What's something you want to buy these days?", text_tr: "Bugünlerde satın almak istediğin bir şey nedir?", type: "question" },
    { id: 56, text_en: "What's a hobby you want to try?", text_tr: "Denemek istediğin bir hobi nedir?", type: "challenge" },
    { id: 57, text_en: "BILINGUAL (answer in two langs)", text_tr: "İKİ DİLLİ (iki dilde cevap ver)", type: "challenge" },
    { id: 58, text_en: "Who is the funniest person you know?", text_tr: "Tanıdığın en komik kişi kim?", type: "question" },
    { id: 59, text_en: "What is the best place to visit in your hometown?", text_tr: "Memleketinde ziyaret edilecek en iyi yer neresidir?", type: "question" },
    { id: 60, text_en: "What is your favorite local restaurant?", text_tr: "En sevdiğin yerel restoran hangisi?", type: "question" },
    { id: 61, text_en: "What's a good name for a boy?", text_tr: "Bir erkek çocuğu için güzel bir isim nedir?", type: "question" },
    { id: 62, text_en: "What's a good name for a girl?", text_tr: "Bir kız çocuğu için güzel bir isim nedir?", type: "question" },
    { id: 63, text_en: "What's your favorite book?", text_tr: "En sevdiğin kitap nedir?", type: "question" },
    { id: 64, text_en: "ONE WORD", text_tr: "TEK KELİME", type: "challenge" },
    { id: 65, text_en: "What's your favorite clothing?", text_tr: "En sevdiğin kıyafetin nedir?", type: "question" },
    { id: 66, text_en: "Who do you talk to everyday?", text_tr: "Her gün kiminle konuşuyorsun?", type: "question" },
    { id: 67, text_en: "Can you whistle?", text_tr: "Islık çalabilir misin?", type: "question" },
    { id: 68, text_en: "What is the best gift you have received?", text_tr: "Aldığın en iyi hediye nedir?", type: "question" },
    { id: 69, text_en: "THERAPY SESSION (everybody answers)", text_tr: "TERAPİ SEANSI (herkes cevaplar)", type: "challenge" },
    { id: 70, text_en: "What's your favorite movie?", text_tr: "En sevdiğin film hangisi?", type: "question" },
    { id: 71, text_en: "ACT IT OUT", text_tr: "CANLANDIR", type: "challenge" },
    { id: 72, text_en: "What's something you won't eat unless you have to?", text_tr: "Mecbur kalmadıkça yemeyeceğin bir şey nedir?", type: "question" },
    { id: 73, text_en: "What's a fun fact about you?", text_tr: "Seninle ilgili eğlenceli bir gerçek nedir?", type: "question" },
    { id: 74, text_en: "What's your favorite dessert?", text_tr: "En sevdiğin tatlı nedir?", type: "question" },
    { id: 75, text_en: "What's something you're good at?", text_tr: "İyi olduğun bir şey nedir?", type: "question" },
    { id: 76, text_en: "RAPID-FIRE (answer three questions)", text_tr: "SERİ ATIŞ (üç soruyu hızlıca cevapla)", type: "challenge" },
    { id: 77, text_en: "What's your favorite story of the week?", text_tr: "Bu haftaki en sevdiğin olay nedir?", type: "question" },
    { id: 78, text_en: "Which social media app do you use the most?", text_tr: "En çok hangi sosyal medya uygulamasını kullanıyorsun?", type: "question" },
    { id: 79, text_en: "Which color do you avoid wearing?", text_tr: "Hangi renk giymekten kaçınırsın?", type: "question" },
    { id: 80, text_en: "Are you an early bird or a night owl?", text_tr: "Erkenci misin yoksa gece kuşu mu?", type: "question" },
    { id: 81, text_en: "What's a useful app on your phone?", text_tr: "Telefonundaki yararlı bir uygulama nedir?", type: "question" },
    { id: 82, text_en: "What's something you do to save money?", text_tr: "Para biriktirmek için yaptığın bir şey nedir?", type: "question" },
    { id: 83, text_en: "Who's someone you admire?", text_tr: "Hayran olduğun biri kim?", type: "question" },
    { id: 84, text_en: "What app do you use the most?", text_tr: "En çok hangi uygulamayı kullanıyorsun?", type: "question" },
    { id: 85, text_en: "DUET (answer together with someone you pick)", text_tr: "DÜET (seçtiğin biriyle birlikte cevap ver)", type: "challenge" },
    { id: 86, text_en: "What kind of books do you like?", text_tr: "Ne tür kitaplardan hoşlanırsın?", type: "question" },
    { id: 87, text_en: "Do you prefer digital or physical?", text_tr: "Dijital mi yoksa fiziksel mi tercih edersin?", type: "question" },
    { id: 88, text_en: "QUESTION SWAP (next player also answers)", text_tr: "SORU DEĞİŞİMİ (sıradaki oyuncu da cevaplar)", type: "challenge" },
    { id: 89, text_en: "Who is the oldest person you know?", text_tr: "Tanıdığın en yaşlı kişi kim?", type: "question" },
    { id: 90, text_en: "What's your favorite meal: breakfast, lunch, or dinner?", text_tr: "En sevdiğin öğün: kahvaltı, öğle veya akşam yemeği?", type: "question" },
    { id: 91, text_en: "Do you like trying new things or sticking to routines?", text_tr: "Yeni şeyler denemeyi mi yoksa rutine bağlı kalmayı mı seversin?", type: "question" },
    { id: 92, text_en: "Do you like taking pictures or recording videos?", text_tr: "Fotoğraf çekmeyi veya video kaydetmeyi sever misin?", type: "question" },
    { id: 93, text_en: "ASK SOMEONE", text_tr: "BİRİNE SOR", type: "challenge" },
    { id: 94, text_en: "What do you do when you feel stressed?", text_tr: "Stresli hissettiğinde ne yaparsın?", type: "question" },
    { id: 95, text_en: "What's your favorite thing to do online?", text_tr: "Çevrimiçi yapmayı en çok sevdiğin şey nedir?", type: "question" },
    { id: 96, text_en: "What kind of movies do you like?", text_tr: "Ne tür filmlerden hoşlanırsın?", type: "question" },
    { id: 97, text_en: "Can you ride a bicycle or motorcycle or a car?", text_tr: "Bisiklet, motosiklet veya araba kullanabilir misin?", type: "question" },
    { id: 98, text_en: "What is your favorite icecream flavor?", text_tr: "En sevdiğin dondurma aroması nedir?", type: "question" },
    { id: 99, text_en: "What makes a good friend?", text_tr: "İyi bir arkadaşı ne oluşturur?", type: "question" },
    { id: 100, text_en: "PICK A QUESTION NUMBER", text_tr: "BİR SORU NUMARASI SEÇ", type: "challenge" }
];
